# Generated by Django 5.2.4 on 2025-09-27 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobs", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="jobseeker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="users.jobseeker",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="users.company",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="jobs.job",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="skills",
            field=models.ManyToManyField(
                blank=True, related_name="jobs", to="jobs.skill"
            ),
        ),
    ]
