# Generated by Django 5.2.4 on 2025-10-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
