# Generated by Django 5.2.4 on 2025-09-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("applied", "Applied"),
                    ("review", "Review"),
                    ("rejected", "Rejected"),
                    ("accepted", "Accepted"),
                    ("interview", "Interview"),
                ],
                default="applied",
                max_length=20,
            ),
        ),
    ]
