# Generated by Django 5.2.4 on 2025-09-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_alter_application_status"),
        ("users", "0003_user_username"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="application",
            options={"ordering": ["-applied_at"]},
        ),
        migrations.AlterModelOptions(
            name="job",
            options={"ordering": ["-posted_at"]},
        ),
        migrations.AddConstraint(
            model_name="application",
            constraint=models.UniqueConstraint(
                fields=("job", "jobseeker"), name="unique_application"
            ),
        ),
    ]
