# Generated by Django 5.2.4 on 2025-10-21 14:33

from django.db import migrations
from django.utils import timezone


def create_skills(apps, schema_editor):
    Skill = apps.get_model("jobs", "Skill")

    skills = [
        {"name": "Python"},
        {"name": "Django"},
        {"name": "React"},
        {"name": "JavaScript"},
        {"name": "HTML"},
        {"name": "CSS"},
        {"name": "SQL"},
        {"name": "Project Management"},
        {"name": "Data Analysis"},
        {"name": "Communication"},
        {"name": "Machine Learning"},
        {"name": "UI/UX Design"},
        {"name": "Marketing"},
        {"name": "Finance"},
        {"name": "Education"},
        {"name": "Engineering"},
        {"name": "Leadership"},
        {"name": "Cloud Computing"},
        {"name": "REST APIs"},
        {"name": "Testing"},
    ]

    for s in skills:
        Skill.objects.get_or_create(
            name=s["name"],
            defaults={"created_at": timezone.now()},
        )


def remove_skills(apps, schema_editor):
    Skill = apps.get_model("jobs", "Skill")
    Skill.objects.filter(
        name__in=[
            "Python",
            "Django",
            "React",
            "JavaScript",
            "HTML",
            "CSS",
            "SQL",
            "Project Management",
            "Data Analysis",
            "Communication",
            "Machine Learning",
            "UI/UX Design",
            "Marketing",
            "Finance",
            "Education",
            "Engineering",
            "Leadership",
            "Cloud Computing",
            "REST APIs",
            "Testing",
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_job_is_open"),
    ]

    operations = [
        migrations.RunPython(create_skills, remove_skills),
    ]
