# Generated by Django 5.2.4 on 2025-10-03 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='saved_jobs',
            field=models.ManyToManyField(blank=True, related_name='saved_by', to='jobs.job'),
        ),
    ]
