# Generated by Django 5.2.4 on 2025-10-03 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_jobseeker_saved_jobs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyrepresentative',
            old_name='role',
            new_name='department',
        ),
    ]
