# Generated by Django 5.2.4 on 2025-09-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobseeker",
            name="about",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobseeker",
            name="education",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="jobseeker",
            name="experience",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="jobseeker",
            name="field_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="jobseeker",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
