# Generated by Django 5.2.4 on 2025-10-18 11:00

from django.db import migrations

def create_companies(apps, schema_editor):
    Company = apps.get_model('users', 'Company')  # Get the Company model safely

    companies = [
        {"name": "Acme Corp", "description": "Leading tech company", "website": "https://acme.com", "location": "New York", "industry": "Technology"},
        {"name": "Globex Inc", "description": "Global logistics solutions", "website": "https://globex.com", "location": "Los Angeles", "industry": "Logistics"},
        {"name": "Initech", "description": "Software solutions provider", "website": "https://initech.com", "location": "San Francisco", "industry": "Software"},
        {"name": "Umbrella Corp", "description": "Pharmaceutical and biotech company", "website": "https://umbrella.com", "location": "Chicago", "industry": "Healthcare"},
        {"name": "Stark Industries", "description": "Advanced engineering and defense", "website": "https://starkindustries.com", "location": "New York", "industry": "Engineering"},
    ]

    for company_data in companies:
        Company.objects.create(**company_data)

def remove_companies(apps, schema_editor):
    Company = apps.get_model('users', 'Company')
    Company.objects.filter(name__in=[
        "Acme Corp", "Globex Inc", "Initech", "Umbrella Corp", "Stark Industries"
    ]).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_role_companyrepresentative_department'),
    ]

    operations = [
        migrations.RunPython(create_companies, remove_companies),
    ]