# Generated by Django 5.2.4 on 2025-10-18 11:25

from django.db import migrations
from django.contrib.auth.hashers import make_password

def create_users(apps, schema_editor):
    # Get the historical User model
    User = apps.get_model("users", "User")

    users = [
        {"email": "roan@gmail.com", "first_name": "Roan", "last_name": "Smith", "password": "password123"},
        {"email": "cleo@gmail.com", "first_name": "Cleo", "last_name": "Johnson", "password": "password123"},
        {"email": "dora@gmail.com", "first_name": "Dora", "last_name": "Williams", "password": "password123"},
        {"email": "dean@gmail.com", "first_name": "Dean", "last_name": "Brown", "password": "password123"},
        {"email": "lea@gmail.com", "first_name": "Lea", "last_name": "Davis", "password": "password123"},
    ]

    for u in users:
        User.objects.get_or_create(
            email=u["email"],
            first_name=u["first_name"],
            last_name=u["last_name"],
            password=make_password(u["password"]),
            is_staff=False,
            is_superuser=False,
        )

    # Create an admin user
    User.objects.get_or_create(
        email="admin@gmail.com",
        first_name="Admin",
        last_name="User",
        password=make_password("admin123"),
        is_staff=True,
        is_superuser=True,
    )

def remove_users(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.filter(email__in=[
        "roan@gmail.com",
        "cleo@gmail.com",
        "dora@gmail.com",
        "dean@gmail.com",
        "lea@gmail.com",
        "admin@gmail.com"
    ]).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20251018_1630'),
    ]

    operations = [
        migrations.RunPython(create_users, remove_users),
    ]
