# Generated by Django 5.2.4 on 2025-10-21 12:29

from django.db import migrations
from django.contrib.auth.hashers import make_password


def create_more_users(apps, schema_editor):
    User = apps.get_model("users", "User")

    new_users = [
        {"email": "maya@gmail.com", "first_name": "Maya", "last_name": "Green", "password": "password123"},
        {"email": "leo@gmail.com", "first_name": "Leo", "last_name": "Martinez", "password": "password123"},
        {"email": "nora@gmail.com", "first_name": "Nora", "last_name": "Adams", "password": "password123"},
        {"email": "oliver@gmail.com", "first_name": "Oliver", "last_name": "Hughes", "password": "password123"},
        {"email": "sophia@gmail.com", "first_name": "Sophia", "last_name": "Turner", "password": "password123"},
    ]

    for u in new_users:
        User.objects.get_or_create(
            email=u["email"],
            defaults={
                "first_name": u["first_name"],
                "last_name": u["last_name"],
                "password": make_password(u["password"]),
                "is_staff": False,
                "is_superuser": False,
            },
        )


def remove_more_users(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.filter(
        email__in=[
            "maya@gmail.com",
            "leo@gmail.com",
            "nora@gmail.com",
            "oliver@gmail.com",
            "sophia@gmail.com",
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_company_company_size_company_email_and_more"),
    ]

    operations = [
        migrations.RunPython(create_more_users, remove_more_users),
    ]
