# Generated by Django 5.2.4 on 2026-01-04 07:02

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_auto_20251021_2034"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobseeker",
            name="resume",
            field=models.FileField(
                blank=True,
                null=True,
                storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                upload_to="resumes/",
            ),
        ),
    ]
