# Generated by Django 5.2.4 on 2026-01-04 07:29

import backend.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_auto_20251021_2034"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobseeker",
            name="resume",
            field=models.FileField(
                blank=True,
                null=True,
                storage=backend.storage.RawCloudinaryStorage(),
                upload_to="resumes/",
            ),
        ),
    ]
